version: '3.8'

services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: meu-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${root123}
      MYSQL_DATABASE: ${sistema_cotacao}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Backend Node.js
  backend:
    build: ./faturacao-saviltech-backend
    container_name: meu-backend
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ${root123}
      DB_NAME: ${sistema_cotacao}
      APP_PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  # Frontend React
  frontend:
    build: ./faturacao-saviltech-frontend
    container_name: meu-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data:
