export const traducoes = {
  pt: {
    bomDia: 'Bom dia',
    boaTarde: 'Boa tarde',
    boaNoite: 'Boa noite',
    dashboard: 'Dashboard',
    criarCotacoes: 'Criar Cotações',
    editarCotacoes: 'Editar Cotações',
    listarCotacoes: 'Listar Cotações',
    facturacao: 'Facturação',
    listarFacturas: 'Listar Facturas',
    editarFacturas: 'Editar Facturas',
    relatorios: 'Relatórios',
    suporte: 'Suporte',
    mensagens: 'Mensagens',
    verMais: 'Ver mais',
    editarPerfil: 'Editar Perfil',
    configuracoes: 'Configurações',
    sair: 'Sair',
    copyright: 'Copyright © 2026 - Todos os direitos reservados',
    criadoPor: 'Criado pela SavilTech Serviços e LDA',
    versao: 'Versão 1.0',
    newsletter: 'Newsletter',
    newsletterPlaceholder: 'O seu email',
    inscrição: 'Inscrever-se',
    bemVindo: 'Bem-vindo',
    cotacoesAberto: 'Cotações em aberto',
    mensagensRecentes: 'Mensagens recentes',
    atualizeDados: 'Atualize os seus dados pessoais.',
    fotoPerfil: 'Foto de perfil',
    semImagem: 'Sem imagem',
    carregarImagem: 'Carregar imagem',
    primeiroNome: 'Primeiro nome',
    apelido: 'Apelido',
    username: 'Username (login)',
    placeholderNome: 'O seu nome',
    placeholderApelido: 'O seu apelido',
    placeholderUsername: 'nome.utilizador',
    alterarSenhaOpc: 'Alterar senha (opcional)',
    senhaAtual: 'Senha atual',
    novaSenha: 'Nova senha',
    guardar: 'Guardar',
    personalizarSistema: 'Personalize o sistema e permissões.',
    coresSistema: 'Cores do sistema',
    altereCores: 'Altere as cores principais da interface.',
    corPrimaria: 'Cor primária',
    corSecundaria: 'Cor secundária',
    aplicarCores: 'Aplicar cores',
    aplicado: 'Aplicado!',
    permissoes: 'Permissões',
    criarUtilizadorDesc: 'Criar novo utilizador e definir o nível de permissão (apenas administradores).',
    senha: 'Senha',
    nivelPermissao: 'Nível de permissão',
    utilizadorFinal: 'Utilizador final',
    administrador: 'Administrador',
    criarUtilizador: 'Criar utilizador',
    preenchaCampos: 'Preencha todos os campos obrigatórios.',
    utilizadorCriado: 'Utilizador criado com sucesso. Pode fazer login com o username e senha definidos.',
    responderMensagens: 'Responda às mensagens dos clientes.',
    resposta: 'Resposta',
    enviar: 'Enviar',
    cancelar: 'Cancelar',
    responder: 'Responder',
    conteudoDesenvolvimento: 'Conteúdo em desenvolvimento.',
    senhaFraca: 'Fraca',
    senhaRazoavel: 'Razoável',
    senhaForte: 'Forte',
    totalCotacoes: 'Total de cotações',
    crescimento: 'crescimento',
    pendentes: 'Pendentes',
    aprovadas: 'Aprovadas',
    rejeitadas: 'Rejeitadas',
    mensagensNovas: 'Mensagens novas',
    distribuicaoEstado: 'Distribuição por estado',
    cotacoesPorMes: 'Cotações por mês',
    cotacoesRecentes: 'Cotações recentes',
    cliente: 'Cliente',
    valor: 'Valor',
    estado: 'Estado',
    data: 'Data',
    tipo: 'Tipo',
    verTodas: 'Ver todas',
    doTotal: 'do total',
    listarDesc: 'Cotações guardadas no sistema. Utilize o ID para localizar e editar.',
    listarDescFacturas: 'Facturas guardadas no sistema. Utilize o ID para localizar e editar.',
    filtroPlaceholder: 'Filtrar por ID, cliente, serviço, valor...',
    todos: 'Todos',
    pessoal: 'Pessoal',
    empresarial: 'Empresarial',
    porPagina: 'por página',
    semCotacoes: 'Ainda não existem cotações guardadas.',
    semFacturas: 'Ainda não existem facturas guardadas.',
    criarPrimeiraCotacao: 'Criar primeira cotação',
    criarPrimeiraFactura: 'Criar primeira factura',
    servico: 'Serviço',
    valorMzn: 'Valor (MZN)',
    totalMzn: 'Total (MZN)',
    accoes: 'Acções',
    editar: 'Editar',
    paginaDe: 'Página',
    editarDesc: 'Pesquise uma cotação por ID, nome do cliente ou serviço e clique para editar no formulário.',
    editarDescFacturas: 'Pesquise uma factura por ID, nome do cliente ou serviço e clique para editar no formulário.',
    pesquisarPlaceholder: 'Pesquisar por ID, nome, serviço, valor...',
    nenhumaEncontrada: 'Nenhuma cotação encontrada para',
    nenhumaFacturaEncontrada: 'Nenhuma factura encontrada para',
    criarCotacao: 'Criar cotação',
    gerarCotacao: 'Gerar cotação',
    criarFactura: 'Criar factura',
    verListarCotacoes: 'Ver Listar Cotações',
    verListarFacturas: 'Ver Listar Facturas',
    cotacaoNaoEncontrada: 'Cotação não encontrada.',
    facturaNaoEncontrada: 'Factura não encontrada.',
    voltarPesquisa: 'Voltar à pesquisa',
    dadosCliente: 'Dados do cliente',
    servicoPeriodo: 'Serviço e período',
    servicoValores: 'Serviço e valores',
    descarregarPdf: 'Descarregar PDF',
    enviarEmail: 'Enviar por Email',
    enviarWhatsApp: 'Enviar por WhatsApp',
    editarNoFormulario: 'Editar no formulário',
    relatoriosDesc: 'Gere um relatório em PDF por período. Escolha o tipo (Cotações ou Facturas) e o intervalo de datas.',
    tipoRelatorio: 'Tipo de relatório',
    relatorioCotacoes: 'Relatório de Cotações',
    relatorioFacturas: 'Relatório de Facturas',
    dataInicio: 'Data de início',
    dataFim: 'Data de fim',
    relatoriosHint: 'Deixe as datas em branco para incluir todos os registos no relatório.',
    relatoriosErroData: 'A data de fim deve ser igual ou posterior à data de início.',
    relatoriosErroGerar: 'Não foi possível gerar o relatório. Tente novamente.',
    gerarRelatorioPdf: 'Gerar relatório (PDF)',
    aGerarPdf: 'A gerar PDF…',
    suporteDesc: 'Perguntas frequentes e formas de contactar a equipa SavilTech.',
    faqTitulo: 'Perguntas frequentes',
    contacteNos: 'Contacte-nos',
    emailDesc: 'Envie-nos um email para apoio geral ou comercial.',
    whatsappSuporte: 'Suporte pelo WhatsApp',
    whatsappHint: 'Clique no nome para abrir o WhatsApp com uma mensagem pré-definida.',
    telefone: 'Telefone',
    telefoneHint: 'Clique no nome para iniciar uma chamada.',
    sms: 'SMS',
    smsHint: 'Clique no nome para abrir o campo de SMS com uma mensagem pré-definida.',
    mensagemPredefinida: 'Olá, preciso de suporte no Sistema de Cotação SavilTech.',
    facturacaoClienteOpcional: 'Cliente existente (opcional)',
    facturacaoPesquisar: 'Pesquisar por nome ou email...',
    tipoPessoal: 'Pessoal',
    tipoPessoalSub: 'Pessoa singular',
    tipoEmpresarial: 'Empresarial',
    tipoEmpresarialSub: 'Empresa ou organização',
    avancarServico: 'Avançar para Serviço Solicitado',
    observacoesNotas: 'Observações ou notas',
    facturacaoServicoTitulo: 'Serviço solicitado',
    facturacaoPeriodoValor: 'Período e valor',
    distribuirValor: 'Distribuição do valor a pagar',
    facturacaoDistribuicaoHint: 'Consoante o valor a cobrar pelo serviço, distribua o total em duas fases e indique a finalidade de cada valor.',
    primeiraFase: '1ª fase',
    segundaFase: '2ª fase',
    finalidadeValor: 'Finalidade deste valor',
    voltarDadosCliente: 'Voltar aos dados do cliente',
    voltarListaFacturas: 'Voltar à lista de facturas',
    gerarFacturaPdf: 'Gerar factura (PDF)',
    guardarAlteracoes: 'Guardar alterações',
    facturaGerada: 'Factura gerada',
    idFactura: 'ID da factura',
    descarregarEnviar: 'Descarregue o PDF e envie por email ou WhatsApp.',
    aCarregar: 'A carregar...',
    editarListaVaziaCotacoes: 'Ainda não existem cotações. Crie uma em Criar Cotações.',
    editarListaVaziaFacturas: 'Ainda não existem facturas. Crie uma em Facturação.',
    abrirFormulario: 'A abrir formulário de edição…',
    faq: [
      { pergunta: 'Como criar uma nova cotação?', resposta: 'Aceda ao menu "Criar Cotações", preencha os dados do cliente (Pessoal ou Empresarial), avance para a seleção do serviço e período, indique o valor proposto e clique em "Gerar cotação". O PDF pode ser enviado por email ou WhatsApp.' },
      { pergunta: 'Onde posso ver e editar as cotações guardadas?', resposta: 'Em "Listar Cotações" verá todas as cotações em tabela, com filtros e paginação. Em "Editar Cotações" pode pesquisar por ID ou nome e, ao clicar numa cotação, visualizar detalhes, descarregar PDF ou abrir o formulário para editar.' },
      { pergunta: 'Como emitir uma factura para um cliente?', resposta: 'Vá a "Facturação", selecione ou registe o cliente, avance para "Serviço solicitado" e preencha o serviço, período, valor a cobrar e IVA. Pode usar "Distribuição do valor a pagar" para duas fases. Gere o PDF e envie por email ou WhatsApp.' },
      { pergunta: 'Onde ficam guardadas as facturas?', resposta: 'As facturas são guardadas localmente no seu browser. Pode listá-las em "Listar Facturas" e editá-las em "Editar Facturas", com a mesma lógica de pesquisa e formulário que nas cotações.' },
      { pergunta: 'Como gerar um relatório em PDF?', resposta: 'Em "Relatórios" escolha o tipo (Cotações ou Facturas), opcionalmente defina o período (data de início e fim) e clique em "Gerar relatório (PDF)". O documento usa o mesmo template da empresa e inclui o resumo dos registos.' },
      { pergunta: 'Os meus dados são guardados na nuvem?', resposta: 'Não. Cotações e facturas são guardadas apenas no armazenamento local do seu navegador (localStorage). Para não perder dados, exporte relatórios em PDF ou faça cópias de segurança conforme necessário.' },
      { pergunta: 'Posso alterar o idioma do sistema?', resposta: 'Sim. No canto superior da aplicação existe um seletor de idioma (Português, Francês, Inglês). A escolha afeta os textos do menu e das páginas que suportam tradução.' },
      { pergunta: 'Como contactar a equipa SavilTech?', resposta: 'Pode enviar email para info@saviltech.com ou usar o suporte por WhatsApp, telefone e SMS através dos contactos indicados nesta página de Suporte. Escolha o canal que preferir.' },
      { pergunta: 'O que fazer se o PDF não abrir ou não for gerado?', resposta: 'Verifique se o seu navegador permite pop-ups ou descargas para este site. Tente gerar novamente; se o problema continuar, contacte o suporte técnico com o tipo de relatório e período que estava a usar.' },
      { pergunta: 'Posso usar o sistema em telemóvel?', resposta: 'Sim. A interface é responsiva e pode ser usada em smartphones e tablets. Os links de WhatsApp, telefone e SMS nesta página abrem as aplicações nativas do dispositivo quando disponíveis.' }
    ]
  },
  fr: {
    bomDia: 'Bonjour',
    boaTarde: 'Bon après-midi',
    boaNoite: 'Bonsoir',
    dashboard: 'Tableau de bord',
    criarCotacoes: 'Créer des devis',
    editarCotacoes: 'Modifier les devis',
    listarCotacoes: 'Lister les devis',
    facturacao: 'Facturation',
    listarFacturas: 'Lister les factures',
    editarFacturas: 'Modifier les factures',
    relatorios: 'Rapports',
    suporte: 'Support',
    mensagens: 'Messages',
    verMais: 'Voir plus',
    editarPerfil: 'Modifier le profil',
    configuracoes: 'Paramètres',
    sair: 'Quitter',
    copyright: 'Copyright © 2026 - Tous droits réservés',
    criadoPor: 'Créé par SavilTech Serviços e LDA',
    versao: 'Version 1.0',
    newsletter: 'Newsletter',
    newsletterPlaceholder: 'Votre email',
    inscrição: "S'inscrire",
    bemVindo: 'Bienvenue',
    cotacoesAberto: 'Devis en cours',
    mensagensRecentes: 'Messages récents',
    atualizeDados: 'Mettez à jour vos données personnelles.',
    fotoPerfil: 'Photo de profil',
    semImagem: 'Sans image',
    carregarImagem: 'Charger une image',
    primeiroNome: 'Prénom',
    apelido: 'Nom',
    username: "Nom d'utilisateur (connexion)",
    placeholderNome: 'Votre prénom',
    placeholderApelido: 'Votre nom',
    placeholderUsername: 'nom.utilisateur',
    alterarSenhaOpc: 'Changer le mot de passe (facultatif)',
    senhaAtual: 'Mot de passe actuel',
    novaSenha: 'Nouveau mot de passe',
    guardar: 'Enregistrer',
    personalizarSistema: 'Personnalisez le système et les permissions.',
    coresSistema: 'Couleurs du système',
    altereCores: 'Modifiez les couleurs principales de l\'interface.',
    corPrimaria: 'Couleur primaire',
    corSecundaria: 'Couleur secondaire',
    aplicarCores: 'Appliquer les couleurs',
    aplicado: 'Appliqué!',
    permissoes: 'Permissions',
    criarUtilizadorDesc: 'Créer un nouvel utilisateur et définir le niveau de permission (administrateurs uniquement).',
    senha: 'Mot de passe',
    nivelPermissao: 'Niveau de permission',
    utilizadorFinal: 'Utilisateur final',
    administrador: 'Administrateur',
    criarUtilizador: 'Créer utilisateur',
    preenchaCampos: 'Remplissez tous les champs obligatoires.',
    utilizadorCriado: 'Utilisateur créé avec succès. Connectez-vous avec le nom d\'utilisateur et le mot de passe définis.',
    responderMensagens: 'Répondez aux messages des clients.',
    resposta: 'Réponse',
    enviar: 'Envoyer',
    cancelar: 'Annuler',
    responder: 'Répondre',
    conteudoDesenvolvimento: 'Contenu en cours de développement.',
    senhaFraca: 'Faible',
    senhaRazoavel: 'Raisonnable',
    senhaForte: 'Forte',
    totalCotacoes: 'Total des devis',
    crescimento: 'croissance',
    pendentes: 'En attente',
    aprovadas: 'Approuvées',
    rejeitadas: 'Rejetées',
    mensagensNovas: 'Nouveaux messages',
    distribuicaoEstado: 'Répartition par état',
    cotacoesPorMes: 'Devis par mois',
    cotacoesRecentes: 'Devis récents',
    cliente: 'Client',
    valor: 'Montant',
    estado: 'État',
    data: 'Date',
    verTodas: 'Voir tout',
    doTotal: 'du total',
    listarDesc: 'Devis enregistrés dans le système. Utilisez l\'ID pour localiser et modifier.',
    listarDescFacturas: 'Factures enregistrées dans le système. Utilisez l\'ID pour localiser et modifier.',
    filtroPlaceholder: 'Filtrer par ID, client, service, montant...',
    todos: 'Tous',
    pessoal: 'Particulier',
    empresarial: 'Entreprise',
    porPagina: 'par page',
    semCotacoes: 'Aucun devis enregistré pour le moment.',
    semFacturas: 'Aucune facture enregistrée pour le moment.',
    criarPrimeiraCotacao: 'Créer le premier devis',
    criarPrimeiraFactura: 'Créer la première facture',
    servico: 'Service',
    valorMzn: 'Montant (MZN)',
    totalMzn: 'Total (MZN)',
    accoes: 'Actions',
    editar: 'Modifier',
    paginaDe: 'Page',
    editarDesc: 'Recherchez un devis par ID, nom du client ou service et cliquez pour modifier dans le formulaire.',
    editarDescFacturas: 'Recherchez une facture par ID, nom du client ou service et cliquez pour modifier dans le formulaire.',
    pesquisarPlaceholder: 'Rechercher par ID, nom, service, montant...',
    nenhumaEncontrada: 'Aucun devis trouvé pour',
    nenhumaFacturaEncontrada: 'Aucune facture trouvée pour',
    criarCotacao: 'Créer un devis',
    criarFactura: 'Créer une facture',
    verListarCotacoes: 'Voir Lister les devis',
    verListarFacturas: 'Voir Lister les factures',
    cotacaoNaoEncontrada: 'Devis non trouvé.',
    facturaNaoEncontrada: 'Facture non trouvée.',
    voltarPesquisa: 'Retour à la recherche',
    dadosCliente: 'Données du client',
    servicoPeriodo: 'Service et période',
    servicoValores: 'Service et valeurs',
    descarregarPdf: 'Télécharger PDF',
    enviarEmail: 'Envoyer par e-mail',
    enviarWhatsApp: 'Envoyer par WhatsApp',
    editarNoFormulario: 'Modifier dans le formulaire',
    relatoriosDesc: 'Générez un rapport en PDF par période. Choisissez le type (Devis ou Factures) et l\'intervalle de dates.',
    tipoRelatorio: 'Type de rapport',
    relatorioCotacoes: 'Rapport des devis',
    relatorioFacturas: 'Rapport des factures',
    dataInicio: 'Date de début',
    dataFim: 'Date de fin',
    relatoriosHint: 'Laissez les dates vides pour inclure tous les enregistrements dans le rapport.',
    relatoriosErroData: 'La date de fin doit être égale ou postérieure à la date de début.',
    relatoriosErroGerar: 'Impossible de générer le rapport. Veuillez réessayer.',
    gerarRelatorioPdf: 'Générer le rapport (PDF)',
    aGerarPdf: 'Génération du PDF…',
    suporteDesc: 'Questions fréquentes et moyens de contacter l\'équipe SavilTech.',
    faqTitulo: 'Questions fréquentes',
    contacteNos: 'Contactez-nous',
    emailDesc: 'Envoyez-nous un e-mail pour l\'assistance générale ou commerciale.',
    whatsappSuporte: 'Support par WhatsApp',
    whatsappHint: 'Cliquez sur le nom pour ouvrir WhatsApp avec un message prédéfini.',
    telefone: 'Téléphone',
    telefoneHint: 'Cliquez sur le nom pour lancer un appel.',
    sms: 'SMS',
    smsHint: 'Cliquez sur le nom pour ouvrir le champ SMS avec un message prédéfini.',
    mensagemPredefinida: 'Bonjour, j\'ai besoin de support pour le système de devis SavilTech.',
    facturacaoClienteOpcional: 'Client existant (optionnel)',
    facturacaoPesquisar: 'Rechercher par nom ou e-mail...',
    tipoPessoal: 'Particulier',
    tipoPessoalSub: 'Personne physique',
    tipoEmpresarial: 'Entreprise',
    tipoEmpresarialSub: 'Entreprise ou organisation',
    avancarServico: 'Passer au service demandé',
    observacoesNotas: 'Remarques ou notes',
    facturacaoServicoTitulo: 'Service demandé',
    facturacaoPeriodoValor: 'Période et montant',
    distribuirValor: 'Répartition du montant à payer',
    facturacaoDistribuicaoHint: 'Selon le montant facturé pour le service, répartissez le total en deux phases et indiquez l\'objet de chaque montant.',
    primeiraFase: '1ère phase',
    segundaFase: '2ème phase',
    finalidadeValor: 'Objet de ce montant',
    voltarDadosCliente: 'Retour aux données du client',
    voltarListaFacturas: 'Retour à la liste des factures',
    gerarFacturaPdf: 'Générer la facture (PDF)',
    guardarAlteracoes: 'Enregistrer les modifications',
    facturaGerada: 'Facture générée',
    idFactura: 'ID de la facture',
    descarregarEnviar: 'Téléchargez le PDF et envoyez par e-mail ou WhatsApp.',
    aCarregar: 'Chargement...',
    editarListaVaziaCotacoes: 'Aucun devis pour le moment. Créez-en un dans Créer des devis.',
    editarListaVaziaFacturas: 'Aucune facture pour le moment. Créez-en une dans Facturation.',
    abrirFormulario: 'Ouverture du formulaire d\'édition…'
  },
  en: {
    bomDia: 'Good morning',
    boaTarde: 'Good afternoon',
    boaNoite: 'Good evening',
    dashboard: 'Dashboard',
    criarCotacoes: 'Create Quotes',
    editarCotacoes: 'Edit Quotes',
    listarCotacoes: 'List Quotes',
    facturacao: 'Invoicing',
    listarFacturas: 'List Invoices',
    editarFacturas: 'Edit Invoices',
    relatorios: 'Reports',
    suporte: 'Support',
    mensagens: 'Messages',
    verMais: 'See more',
    editarPerfil: 'Edit Profile',
    configuracoes: 'Settings',
    sair: 'Sign out',
    copyright: 'Copyright © 2026 - All rights reserved',
    criadoPor: 'Created by SavilTech Serviços e LDA',
    versao: 'Version 1.0',
    newsletter: 'Newsletter',
    newsletterPlaceholder: 'Your email',
    inscrição: 'Subscribe',
    bemVindo: 'Welcome',
    cotacoesAberto: 'Open quotes',
    mensagensRecentes: 'Recent messages',
    atualizeDados: 'Update your personal data.',
    fotoPerfil: 'Profile photo',
    semImagem: 'No image',
    carregarImagem: 'Upload image',
    primeiroNome: 'First name',
    apelido: 'Last name',
    username: 'Username (login)',
    placeholderNome: 'Your first name',
    placeholderApelido: 'Your last name',
    placeholderUsername: 'username',
    alterarSenhaOpc: 'Change password (optional)',
    senhaAtual: 'Current password',
    novaSenha: 'New password',
    guardar: 'Save',
    personalizarSistema: 'Customize the system and permissions.',
    coresSistema: 'System colors',
    altereCores: 'Change the main interface colors.',
    corPrimaria: 'Primary color',
    corSecundaria: 'Secondary color',
    aplicarCores: 'Apply colors',
    aplicado: 'Applied!',
    permissoes: 'Permissions',
    criarUtilizadorDesc: 'Create new user and set permission level (administrators only).',
    senha: 'Password',
    nivelPermissao: 'Permission level',
    utilizadorFinal: 'End user',
    administrador: 'Administrator',
    criarUtilizador: 'Create user',
    preenchaCampos: 'Fill in all required fields.',
    utilizadorCriado: 'User created successfully. You can log in with the username and password set.',
    responderMensagens: 'Reply to client messages.',
    resposta: 'Reply',
    enviar: 'Send',
    cancelar: 'Cancel',
    responder: 'Reply',
    conteudoDesenvolvimento: 'Content under development.',
    senhaFraca: 'Weak',
    senhaRazoavel: 'Fair',
    senhaForte: 'Strong',
    totalCotacoes: 'Total quotes',
    crescimento: 'growth',
    pendentes: 'Pending',
    aprovadas: 'Approved',
    rejeitadas: 'Rejected',
    mensagensNovas: 'New messages',
    distribuicaoEstado: 'Distribution by status',
    cotacoesPorMes: 'Quotes per month',
    cotacoesRecentes: 'Recent quotes',
    cliente: 'Client',
    valor: 'Amount',
    estado: 'Status',
    data: 'Date',
    tipo: 'Type',
    verTodas: 'View all',
    doTotal: 'of total',
    listarDesc: 'Quotes saved in the system. Use the ID to find and edit.',
    listarDescFacturas: 'Invoices saved in the system. Use the ID to find and edit.',
    filtroPlaceholder: 'Filter by ID, client, service, amount...',
    todos: 'All',
    pessoal: 'Personal',
    empresarial: 'Business',
    porPagina: 'per page',
    semCotacoes: 'No quotes saved yet.',
    semFacturas: 'No invoices saved yet.',
    criarPrimeiraCotacao: 'Create first quote',
    criarPrimeiraFactura: 'Create first invoice',
    servico: 'Service',
    valorMzn: 'Amount (MZN)',
    totalMzn: 'Total (MZN)',
    accoes: 'Actions',
    editar: 'Edit',
    paginaDe: 'Page',
    editarDesc: 'Search for a quote by ID, client name or service and click to edit in the form.',
    editarDescFacturas: 'Search for an invoice by ID, client name or service and click to edit in the form.',
    pesquisarPlaceholder: 'Search by ID, name, service, amount...',
    nenhumaEncontrada: 'No quote found for',
    nenhumaFacturaEncontrada: 'No invoice found for',
    criarCotacao: 'Create quote',
    gerarCotacao: 'Generate quote',
    criarFactura: 'Create invoice',
    verListarCotacoes: 'View List Quotes',
    verListarFacturas: 'View List Invoices',
    cotacaoNaoEncontrada: 'Quote not found.',
    facturaNaoEncontrada: 'Invoice not found.',
    voltarPesquisa: 'Back to search',
    dadosCliente: 'Client details',
    servicoPeriodo: 'Service and period',
    servicoValores: 'Service and values',
    descarregarPdf: 'Download PDF',
    enviarEmail: 'Send by Email',
    enviarWhatsApp: 'Send by WhatsApp',
    editarNoFormulario: 'Edit in form',
    relatoriosDesc: 'Generate a PDF report by period. Choose the type (Quotes or Invoices) and the date range.',
    tipoRelatorio: 'Report type',
    relatorioCotacoes: 'Quotes Report',
    relatorioFacturas: 'Invoices Report',
    dataInicio: 'Start date',
    dataFim: 'End date',
    relatoriosHint: 'Leave dates blank to include all records in the report.',
    relatoriosErroData: 'End date must be equal to or after start date.',
    relatoriosErroGerar: 'Could not generate the report. Please try again.',
    gerarRelatorioPdf: 'Generate report (PDF)',
    aGerarPdf: 'Generating PDF…',
    suporteDesc: 'Frequently asked questions and ways to contact the SavilTech team.',
    faqTitulo: 'Frequently asked questions',
    contacteNos: 'Contact us',
    emailDesc: 'Send us an email for general or sales support.',
    whatsappSuporte: 'Support via WhatsApp',
    whatsappHint: 'Click on the name to open WhatsApp with a predefined message.',
    telefone: 'Phone',
    telefoneHint: 'Click on the name to start a call.',
    sms: 'SMS',
    smsHint: 'Click on the name to open the SMS field with a predefined message.',
    mensagemPredefinida: 'Hello, I need support with the SavilTech Quote System.',
    facturacaoClienteOpcional: 'Existing client (optional)',
    facturacaoPesquisar: 'Search by name or email...',
    tipoPessoal: 'Personal',
    tipoPessoalSub: 'Individual',
    tipoEmpresarial: 'Business',
    tipoEmpresarialSub: 'Company or organisation',
    avancarServico: 'Continue to Service Requested',
    observacoesNotas: 'Remarks or notes',
    facturacaoServicoTitulo: 'Service requested',
    facturacaoPeriodoValor: 'Period and amount',
    distribuirValor: 'Distribution of amount to pay',
    facturacaoDistribuicaoHint: 'According to the amount charged for the service, distribute the total in two phases and indicate the purpose of each amount.',
    primeiraFase: '1st phase',
    segundaFase: '2nd phase',
    finalidadeValor: 'Purpose of this amount',
    voltarDadosCliente: 'Back to client details',
    voltarListaFacturas: 'Back to invoice list',
    gerarFacturaPdf: 'Generate invoice (PDF)',
    guardarAlteracoes: 'Save changes',
    facturaGerada: 'Invoice generated',
    idFactura: 'Invoice ID',
    descarregarEnviar: 'Download the PDF and send by email or WhatsApp.',
    aCarregar: 'Loading...',
    editarListaVaziaCotacoes: 'No quotes yet. Create one in Create Quotes.',
    editarListaVaziaFacturas: 'No invoices yet. Create one in Invoicing.',
    abrirFormulario: 'Opening edit form…',
    faq: [
      { pergunta: 'How do I create a new quote?', resposta: 'Go to the "Create Quotes" menu, fill in the client details (Personal or Business), proceed to service and period selection, enter the proposed value and click "Generate quote". The PDF can be sent by email or WhatsApp.' },
      { pergunta: 'Where can I view and edit saved quotes?', resposta: 'In "List Quotes" you will see all quotes in a table, with filters and pagination. In "Edit Quotes" you can search by ID or name and, by clicking on a quote, view details, download PDF or open the form to edit.' },
      { pergunta: 'How do I issue an invoice for a client?', resposta: 'Go to "Invoicing", select or register the client, proceed to "Service requested" and fill in the service, period, amount to charge and VAT. You can use "Distribution of amount to pay" in two phases. Generate the PDF and send by email or WhatsApp.' },
      { pergunta: 'Where are invoices stored?', resposta: 'Invoices are stored locally in your browser. You can list them in "List Invoices" and edit them in "Edit Invoices", with the same search and form logic as for quotes.' },
      { pergunta: 'How do I generate a PDF report?', resposta: 'In "Reports" choose the type (Quotes or Invoices), optionally set the period (start and end date) and click "Generate report (PDF)". The document uses the same company template and includes the summary of records.' },
      { pergunta: 'Are my data stored in the cloud?', resposta: 'No. Quotes and invoices are stored only in your browser\'s local storage (localStorage). To avoid losing data, export reports to PDF or make backups as needed.' },
      { pergunta: 'Can I change the system language?', resposta: 'Yes. In the top corner of the application there is a language selector (Portuguese, French, English). The choice affects the menu texts and pages that support translation.' },
      { pergunta: 'How do I contact the SavilTech team?', resposta: 'You can send an email to info@saviltech.com or use support via WhatsApp, phone and SMS through the contacts shown on this Support page. Choose the channel you prefer.' },
      { pergunta: 'What to do if the PDF does not open or is not generated?', resposta: 'Check that your browser allows pop-ups or downloads for this site. Try generating again; if the problem continues, contact technical support with the report type and period you were using.' },
      { pergunta: 'Can I use the system on mobile?', resposta: 'Yes. The interface is responsive and can be used on smartphones and tablets. The WhatsApp, phone and SMS links on this page open the device\'s native apps when available.' }
    ]
  }
}
